apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    uid: shittytoken-prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Gateway API
    type: yesoreyeram-infinity-datasource
    uid: shittytoken-infinity
    access: proxy
    editable: true
    jsonData:
      global_queries: []
